spring:
  application:
    name: hadoop
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080


#hdfs:
#  path: hdfs://192.168.2.2:9000
#  username: root

hdfs:
  path: hdfs://172.16.104.204:9000
  username: hadoop